language: java
install: mvn -U install clean --fail-never --quiet -DskipTests=true -Dinvoker.skip=true
script: mvn verify

jdk:
  - openjdk7
  - oraclejdk7

notifications:
  email: false

branches:
  except:
    - gh-pages
